### ISSUE TITLE
Implement support for Facebook's ram-bundle sourcemaps

### ISSUE THREAD

**Issue by mitsuhiko** [getsentry/rust-sourcemap#15]
Facebook added an extension to the sourcemap format (`x_facebook_offsets` and `x_metro_module_paths`). I'm not yet sure how to best support this here, but it's a thing now for react native.

This was originally reported here: https://github.com/getsentry/sentry-cli/issues/408

**Comment by ButtersHub** [comment]
Hi @mitsuhiko, is there any updates on that issue, can we help somehow on that?

**Comment by mitsuhiko** [comment]
@ButtersHub there are no updates yet. I can't promise yet when I will have a look at it. We're pushing out a major update in other areas right now so not sure if I can promise anything right now.

If you want to help out I think we need to work on this in stages anyways. The first step will be to add a new source map format internally similarly to how we deal with indexes that represents a Ram-Bundle and then parse it.

From there we can have a look at if we can find a unified interface for all three formats. For sentry's use I would like to rewrite it into a normal sourcemap but I'm not sure yet if that is possible.
