### ISSUE TITLE
Please publish a new version

### ISSUE THREAD

**Issue by kdy1** [getsentry/rust-sourcemap#30]
I need https://github.com/getsentry/rust-sourcemap/pull/25 as it's very important for performance

**Comment by kamilogorek** [comment]
We'll do that on Monday. Cheers!

**Comment by kdy1** [comment]
@kamilogorek Great, thanks!

**Comment by Swatinem** [comment]
Published `6.0.0` with just minimal breakage; see the CHANGELOG.

**Comment by kdy1** [comment]
Thanks a lot!
