### ISSUE TITLE
Sourcemap locations may be resolved incorrectly in Firefox

### ISSUE THREAD

**Issue by robertknight** [getsentry/rust-sourcemap#37]
Please consider this issue an FYI for other Sentry users as much as anything else, since I think the fix will happen in Firefox.

We recently ran into a problem where JavaScript crash reports from Firefox were resolved to the wrong location in the original code. The issue turned out to be that Firefox expresses column numbers in stack traces differently than other browsers. Chrome and Safari report the column number in UTF-16 code units, whereas Firefox reports them in Unicode code points. From what I can tell, this package assumes UTF-16 code units. If a minified source bundle contains many characters (eg. emojis) that require multiple UTF-16 characters to encode, this can result in incorrectly resolved source locations when processing crash reports in Firefox.

I filed an issue at https://github.com/tc39/proposal-error-stacks/issues/42 and https://bugzilla.mozilla.org/show_bug.cgi?id=1746374 to try to find an upstream resolution.

**Comment by mitsuhiko** [comment]
I left a comment now on the tc39 proposal. I hope for now that Firefox reverts this behavior but the issue is known from our side. Since not all Firefox versions agree on the offset it's unfortunately a pretty frustrating situation right now that we do not want to try to make too many guesses about.

**Comment by tobias-wilfert** [comment]
Seems like this is already fixed, feel free to reopen if that is not the case.
