### ISSUE TITLE
Weekly CI reports errors to me still

### ISSUE THREAD

**Issue by flub** [getsentry/rust-sourcemap#57]
Hello, the weekly CI job is still reporting errors to me.  Probably because I last edited the file...  I guess you have a few options:

- Don't care anymore: remove it
- Push a commit to the file and receive the errors
- Make the job report a bug instead of only relying on this strange notification routing, that's what I do currently and works pretty well.  e.g. https://github.com/n0-computer/iroh/blob/main/.github/workflows/weekly.yml#L49-L56

**Comment by Swatinem** [comment]
Thanks for reminding me! #58 renames the file so you shouldn’t be notified anymore.

We are also trying to dogfood our github actions transaction integration and creating some alerting for that, which works so-so right now:

![grafik](https://user-images.githubusercontent.com/580492/209118345-43e4a666-6b15-4a8b-a443-2fb5665b7449.png)

For some reasons it is not yet triggering reliably for all the projects that are failing the weekly CI runs. CC @asottile-sentry
