### ISSUE TITLE
results from SourceMap::lookup_token is not correct

### ISSUE THREAD

**Issue by Brooooooklyn** [getsentry/rust-sourcemap#7]
you can find a playground project in https://github.com/Brooooooklyn/sourcemap-issue

and `yarn && yarn start` to see the follow result:

```rust
let s = sm.lookup_token(1, 113946).unwrap()
println!("content: {}, column: {}", s.get_source().unwrap(), s.get_src_line());
// '../static/js/main.4a1cd49f.js', 2357
```

and the result from https://www.npmjs.com/package/source-map:

```js
const jsDecoder = new SourceMapConsumer(sourcemap)
const jsResult = jsDecoder.originalPositionFor({
  line: 1,
  column: 113946
})

console.log(jsResult)
// { source: 'service.ts', line: 10, column: 0, name: null }

```

**Comment by Brooooooklyn** [comment]
@mitsuhiko

**Comment by mitsuhiko** [comment]
The line and column are zero indexed on lookup. Presumably you are passing wrong data.

**Comment by Brooooooklyn** [comment]
that's wired, because the same file is decoded correctly by https://www.npmjs.com/package/source-map

**Comment by mitsuhiko** [comment]
@Brooooooklyn not sure what you mean. this library intentionally uses zero indexed values so you are passing the wrong values into the lookup functions.

**Comment by mitsuhiko** [comment]
To clarify that: if you want to look up line 1 and column 1 you need to pass `(0, 0)` and not `(1, 1)`.

**Comment by Brooooooklyn** [comment]
Oh, I get it , sorry for my misunderstanding.
